import './globals.css'
import { Inter } from 'next/font/google'
import "tw-elements/dist/css/tw-elements.min.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <script
          type="text/javascript"
          src="@node_modules/tw-elements/dist/js/tw-elements.umd.min.js"></script>
      </body>
    </html>
  )
}
